# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: #ao mudar branch main pipeline executa automaticamente
- main

resources:
- repo: self

variables:
  tag: 123  #assumi a versao da imagem docker com um numero sequencial

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest #imagem usada
    steps:
    - task: Docker@2
      displayName: Build e Push no Docker Hub do Azure na Highlander
      inputs:
        containerRegistry: 'high-dockerhub'
        repository: 'highlanderhr7/novaimagemcriada:latest'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest